apiVersion: v1
kind: Pod
metadata:
  name: streamlit-pod
  labels:
    app: streamlit
spec:
  containers:
    - name: streamlit
      image: refaelsaidov1/week_11_k8s_test:0.0.1
      ports:
        - containerPort: 8080